// src/types/routes.ts

import { DayItinerary } from "./itinerary";

/**
 * A single label/highlight for a route option
 */
export interface RouteHighlight {
  label: string;
  icon?: string;
}

/**
 * A single route option
 */
export interface RouteOption {
  id: string;
  badge: string; // e.g., "🏛️ Classic Route"
  badgeColor?: string; // e.g., "#667eea"
  title: string;
  description: string;
  highlights: RouteHighlight[];
  days: number;
  estimatedBudget?: string;
  intensity?: "easy" | "moderate" | "high";
  itinerary: DayItinerary[]; // Full itinerary data
}

/**
 * Multi-route response generated by AI
 */
export interface MultiRouteResponse {
  destination: string;
  startDate: string;
  endDate: string;
  routes: RouteOption[];
}

/**
 * Route generation request parameters
 */
export interface RouteGenerationRequest {
  destination: string;
  travelStartDate: string;
  travelEndDate: string;
  travelers: string;
  travelType: string[];
  transportation: string[];
  activityIntensity: string;
  specialNeeds: string[];
  userId: string;
}
